codecov:
  notify:
    require_ci_to_pass: yes
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: yes
      unit:
        target: auto
        flags:
          - unit
      integration:
        target: auto
        flags:
          - integration
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

flags:
  flag:
    carryforward: true
  flagonebaby:
    carryforward: true

comment:
  layout: "header, diff, footer"
  behavior: default
  require_changes: no
  require_base: no
